### ISSUE TITLE
Errors on post request

### ISSUE THREAD

**Issue by pakman198** [mickleroy/grunt-clientlibify#2]
Hello
I'been trying to use the plugin and i can't make it work, i constantly get
- read ECONNRESET
- 403 target service not allowed

I don't get why i keep getting but i think is because at the office we have a proxy.
I tried using the plugin at home and it worked perfectly.
Do you have an idea of how i can make this work?
Thanks in advance.

**Comment by mickleroy** [comment]
Thanks for reaching out.

grunt-clientlibify makes use of the [request](https://github.com/request/request) node module which understands various proxy related environment variables. May I suggest you tweak your HTTP_PROXY, HTTPS_PROXY variables and check if it makes a difference.
More info [here](https://github.com/request/request#proxies).

Cheers

**Comment by mickleroy** [comment]
For your information, I wasn't able to reproduce your problem but I did attempt to use the plugin at work (uses a proxy) and the upload was successful once I specified the NO_PROXY=localhost environment variable. 

Hope this helps

**Comment by pakman198** [comment]
Hi @mickleroy thanks for replying.
I will set the _**NO_PROXY=localhost**_ environment variable, the HTTP_PROXY and the HTTPS_PROXY variables were set when I got the computer.
I'll restart the machine and see if something changes.

Regards

**Comment by pakman198** [comment]
@mickleroy you're like GOD, it worked !!!!!
yeah the **NO_PROXY** environment  variable was solution.
Thank you so much for your help, i've been working with this for a week and i was about to forget about this enhancement to the development.

Have a nice day !
